package com.cashmallow.api.domain.shared;

public class MsgCode {
    public static final String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    public static final String TRAVELER_CANNOT_FIND_BY_USER_ID = "TRAVELER_CANNOT_FIND_BY_USER_ID";
    public static final String OLD_VERSION_APP_ERROR = "OLD_VERSION_APP_ERROR";
    public static final String CASHOUT_IN_PROGRESS = "CASHOUT_IN_PROGRESS";
    public static final String CASHOUT_NOT_IN_PROGRESS_UNAVAILABLE_CANCEL = "CASHOUT_NOT_IN_PROGRESS_UNAVAILABLE_CANCEL";
    public static final String CASHOUT_ERROR_REQUEST_STOPPED_SERVICE = "CASHOUT_ERROR_REQUEST_STOPPED_SERVICE";
    public static final String REJECT_EXCHANGE_REMITTANCE_ERROR = "REJECT_EXCHANGE_REMITTANCE_ERROR";

    public static final String TRAVELER_DUPLICATE_PASSPORT = "TRAVELER_DUPLICATE_PASSPORT";
    public static final String TRAVELER_DUPLICATE_IDCARD = "TRAVELER_DUPLICATE_IDCARD";

    public static final String DELETED_API = "DELETED_API";

    public static final String TRAVELER_INVALID_JOB = "TRAVELER_INVALID_JOB";
    public static final String REFUND_ERROR_REQUEST_PROCESS_IN_EXCHANGE = "REFUND_ERROR_REQUEST_PROCESS_IN_EXCHANGE";
    public static final String TRAVELER_REFUND_BANK_ACCOUNT_RE_VERIFICATION = "TRAVELER_REFUND_BANK_ACCOUNT_RE_VERIFICATION";

    public static final String ML_INVALID_QR_CODE = "ML_INVALID_QR_CODE";
    public static final String INVALID_ATM = "INVALID_ATM";

    public static final String PREVIOUS_EXCHANGE_IN_PROGRESS = "PREVIOUS_EXCHANGE_IN_PROGRESS";
    public static final String PREVIOUS_REMITTANCE_IN_PROGRESS = "PREVIOUS_REMITTANCE_IN_PROGRESS";

    public static final String EXCHANGE_CHANGED_EXCHANGE_RATE = "EXCHANGE_CHANGED_EXCHANGE_RATE";

    public static final String JP_REFUND_IN_PROGRESS_NOT_CHANGE_ACCOUNT = "JP_REFUND_IN_PROGRESS_NOT_CHANGE_ACCOUNT";

    public static final String NOT_FOUND_PASSPORT_COUNTRY_CODE ="NOT_FOUND_PASSPORT_COUNTRY_CODE";

    public static final String INVALID_REGION_VALUE = "INVALID_REGION_VALUE";
}
