package com.cashmallow.api.domain.model.country.enums;

import com.cashmallow.api.domain.shared.CashmallowException;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;

import java.io.Serializable;
import java.util.Arrays;

import static com.cashmallow.api.domain.shared.MsgCode.NOT_FOUND_PASSPORT_COUNTRY_CODE;

/**
 * 회원가입시 사용할 iso3166 값등 국가 정보
 * 순서대로 노출됨.
 */

@Slf4j
@AllArgsConstructor
@Getter
public enum Country3 implements Serializable {
    KOR("South Korea", "410", "KR", "KOR", "+82", "KRW", "AS"),
    HKG("Hong Kong", "344", "HK", "HKG", "+852", "HKD", "AS"),

    AFG("Afghanistan", "004", "AF", "AFG", "+93", "AFN", "AS"),
    ALB("Albania", "008", "AL", "ALB", "+355", "ALL", "EU"),
    DZA("Algeria", "012", "DZ", "DZA", "+213", "DZD", "AF"),
    ASM("American Samoa", "016", "AS", "ASM", "+684", "USD", "OC"),
    AND("Andorra", "020", "AD", "AND", "+376", "EUR", "EU"),
    AGO("Angola", "024", "AO", "AGO", "+244", "AOA", "AF"),
    AIA("Anguilla", "660", "AI", "AIA", "+264", "XCD", "NA"),
    ATA("Antarctica", "010", "AQ", "ATA", "+672", "AUD", "AN"),
    ATG("Antigua & Barbuda", "028", "AG", "ATG", "+268", "XCD", "NA"),
    ARG("Argentina", "032", "AR", "ARG", "+54", "ARS", "SA"),
    ARM("Armenia", "051", "AM", "ARM", "+374", "AMD", "AS"),
    ABW("Aruba", "533", "AW", "ABW", "+297", "AWG", "NA"),
    AUS("Australia", "036", "AU", "AUS", "+61", "AUD", "OC"),
    AUT("Austria", "040", "AT", "AUT", "+43", "EUR", "EU"),
    AZE("Azerbaijan", "031", "AZ", "AZE", "+994", "AZN", "AS"),
    BHS("Bahamas", "044", "BS", "BHS", "+242", "BSD", "NA"),
    BHR("Bahrain", "048", "BH", "BHR", "+973", "BHD", "AS"),
    BGD("Bangladesh", "050", "BD", "BGD", "+880", "BDT", "AS"),
    BRB("Barbados", "052", "BB", "BRB", "+246", "BBD", "NA"),
    BLR("Belarus", "112", "BY", "BLR", "+375", "BYR", "EU"),
    BEL("Belgium", "056", "BE", "BEL", "+32", "EUR", "EU"),
    BLZ("Belize", "084", "BZ", "BLZ", "+501", "BZD", "NA"),
    BEN("Benin", "204", "BJ", "BEN", "+229", "XOF", "AF"),
    BMU("Bermuda", "060", "BM", "BMU", "+441", "BMD", "NA"),
    BTN("Bhutan", "064", "BT", "BTN", "+975", "BTN", "AS"),
    BOL("Bolivia", "068", "BO", "BOL", "+591", "BOB", "SA"),
    BIH("Bosnia & Herzegovina", "070", "BA", "BIH", "+387", "BAM", "EU"),
    BWA("Botswana", "072", "BW", "BWA", "+267", "BWP", "AF"),
    BRA("Brazil", "076", "BR", "BRA", "+55", "BRL", "SA"),
    VGB("British Virgin Islands", "092", "VG", "VGB", "+1", "USD", "NA"),
    BRN("Brunei", "096", "BN", "BRN", "+673", "BND", "AS"),
    BGR("Bulgaria", "100", "BG", "BGR", "+359", "BGN", "EU"),
    BFA("Burkina Faso", "854", "BF", "BFA", "+226", "XOF", "AF"),
    BDI("Burundi", "108", "BI", "BDI", "+257", "BIF", "AF"),
    KHM("Cambodia", "116", "KH", "KHM", "+855", "KHR", "AS"),
    CMR("Cameroon", "120", "CM", "CMR", "+237", "XAF", "AF"),
    CAN("Canada", "124", "CA", "CAN", "+1", "CAD", "NA"),
    CPV("Cabo Verde", "132", "CV", "CPV", "+238", "CVE", "AF"),
    CYM("Cayman Islands", "136", "KY", "CYM", "+345", "KYD", "NA"),
    CAF("Central African Republic", "140", "CF", "CAF", "+236", "XAF", "AF"),
    TCD("Chad", "148", "TD", "TCD", "+235", "XAF", "AF"),
    CHL("Chile", "152", "CL", "CHL", "+56", "CLP", "SA"),
    CHN("China", "156", "CN", "CHN", "+86", "CNY", "AS"),
    COL("Colombia", "170", "CO", "COL", "+57", "COP", "SA"),
    COM("Comoros", "174", "KM", "COM", "+269", "KMF", "AF"),
    COG("Congo - Brazzaville", "178", "CG", "COG", "+242", "XAF", "AF"),
    COD("Congo - Kinshasa", "180", "CD", "COD", "+243", "CDF", "AF"),
    COK("Cook Islands", "184", "CK", "COK", "+682", "NZD", "OC"),
    CRI("Costa Rica", "188", "CR", "CRI", "+506", "CRC", "NA"),
    CIV("Côte d'Ivoire", "384", "CI", "CIV", "+225", "XOF", "AF"),
    HRV("Croatia", "191", "HR", "HRV", "+385", "HRK", "EU"),
    CUB("Cuba", "192", "CU", "CUB", "+53", "CUP", "NA"),
    CUW("Curaçao", "531", "CW", "CUW", "+599", "ANG", ""),
    CYP("Cyprus", "196", "CY", "CYP", "+357", "EUR", "AS"),
    CZE("Czech Republic", "203", "CZ", "CZE", "+420", "CZK", "EU"),
    DNK("Denmark", "208", "DK", "DNK", "+45", "DKK", "EU"),
    DJI("Djibouti", "262", "DJ", "DJI", "+253", "DJF", "AF"),
    DMA("Dominica", "212", "DM", "DMA", "+767", "XCD", "NA"),
    DOM("Dominican Republic", "214", "DO", "DOM", "+809", "DOP", "NA"),
    ECU("Ecuador", "218", "EC", "ECU", "+593", "USD", "SA"),
    EGY("Egypt", "818", "EG", "EGY", "+20", "EGP", "AF"),
    SLV("El Salvador", "222", "SV", "SLV", "+503", "SVC", "NA"),
    GNQ("Equatorial Guinea", "226", "GQ", "GNQ", "+240", "XAF", "AF"),
    ERI("Eritrea", "232", "ER", "ERI", "+291", "ETB", "AF"),
    EST("Estonia", "233", "EE", "EST", "+372", "EUR", "EU"),
    ETH("Ethiopia", "231", "ET", "ETH", "+251", "ETB", "AF"),
    FLK("Falkland Islands", "238", "FK", "FLK", "+500", "FKP", "SA"),
    FRO("Faroe Islands", "234", "FO", "FRO", "+298", "DKK", "EU"),
    FJI("Fiji", "242", "FJ", "FJI", "+679", "FJD", "OC"),
    FIN("Finland", "246", "FI", "FIN", "+358", "EUR", "EU"),
    FRA("France", "250", "FR", "FRA", "+33", "EUR", "EU"),
    GUF("French Guiana", "254", "GF", "GUF", "+594", "EUR", "SA"),
    PYF("French Polynesia", "258", "PF", "PYF", "+689", "XPF", "OC"),
    GAB("Gabon", "266", "GA", "GAB", "+241", "XAF", "AF"),
    GMB("Gambia", "270", "GM", "GMB", "+220", "GMD", "AF"),
    GEO("Georgia", "268", "GE", "GEO", "+995", "GEL", "AS"),
    DEU("Germany", "276", "DE", "DEU", "+49", "EUR", "EU"),
    GHA("Ghana", "288", "GH", "GHA", "+233", "GHS", "AF"),
    GIB("Gibraltar", "292", "GI", "GIB", "+350", "GIP", "EU"),
    GRC("Greece", "300", "GR", "GRC", "+30", "EUR", "EU"),
    GRL("Greenland", "304", "GL", "GRL", "+299", "DKK", "NA"),
    GRD("Grenada", "308", "GD", "GRD", "+473", "XCD", "NA"),
    GLP("Guadeloupe", "312", "GP", "GLP", "+590", "EUR", "NA"),
    GUM("Guam", "316", "GU", "GUM", "+671", "USD", "OC"),
    GTM("Guatemala", "320", "GT", "GTM", "+502", "GTQ", "NA"),
    GGY("Guernsey", "831", "GG", "GGY", "+1481", "GGP", "EU"),
    GIN("Guinea", "324", "GN", "GIN", "+225", "GNF", "AF"),
    GNB("Guinea-Bissau", "624", "GW", "GNB", "+245", "XOF", "AF"),
    GUY("Guyana", "328", "GY", "GUY", "+592", "GYD", "SA"),
    HTI("Haiti", "332", "HT", "HTI", "+509", "HTG", "NA"),
    HND("Honduras", "340", "HN", "HND", "+504", "HNL", "NA"),
    HUN("Hungary", "348", "HU", "HUN", "+36", "HUF", "EU"),
    ISL("Iceland", "352", "IS", "ISL", "+354", "ISK", "EU"),
    IND("India", "356", "IN", "IND", "+91", "INR", "AS"),
    IDN("Indonesia", "360", "ID", "IDN", "+62", "IDR", "AS"),
    IRN("Iran", "364", "IR", "IRN", "+98", "IRR", "AS"),
    IRQ("Iraq", "368", "IQ", "IRQ", "+964", "IQD", "AS"),
    IRL("Ireland", "372", "IE", "IRL", "+353", "EUR", "EU"),
    ISR("Israel", "376", "IL", "ISR", "+972", "ILS", "AS"),
    ITA("Italy", "380", "IT", "ITA", "+39", "EUR", "EU"),
    JAM("Jamaica", "388", "JM", "JAM", "+876", "JMD", "NA"),
    JPN("Japan", "392", "JP", "JPN", "+81", "JPY", "AS"),
    JOR("Jordan", "400", "JO", "JOR", "+962", "JOD", "AS"),
    KAZ("Kazakhstan", "398", "KZ", "KAZ", "+7", "KZT", "AS"),
    KEN("Kenya", "404", "KE", "KEN", "+254", "KES", "AF"),
    KIR("Kiribati", "296", "KI", "KIR", "+686", "AUD", "OC"),
    KWT("Kuwait", "414", "KW", "KWT", "+965", "KWD", "AS"),
    KGZ("Kyrgyzstan", "417", "KG", "KGZ", "+996", "KGS", "AS"),
    LAO("Laos", "418", "LA", "LAO", "+856", "LAK", "AS"),
    LVA("Latvia", "428", "LV", "LVA", "+371", "EUR", "EU"),
    LBN("Lebanon", "422", "LB", "LBN", "+961", "LBP", "AS"),
    LSO("Lesotho", "426", "LS", "LSO", "+266", "LSL", "AF"),
    LBR("Liberia", "430", "LR", "LBR", "+231", "LRD", "AF"),
    LBY("Libya", "434", "LY", "LBY", "+218", "LYD", "AF"),
    LIE("Liechtenstein", "438", "LI", "LIE", "+423", "CHF", "EU"),
    LTU("Lithuania", "440", "LT", "LTU", "+370", "LTL", "EU"),
    LUX("Luxembourg", "442", "LU", "LUX", "+352", "EUR", "EU"),
    MAC("Macao", "446", "MO", "MAC", "+853", "MOP", "AS"),
    MKD("Macedonia", "807", "MK", "MKD", "+389", "MKD", "EU"),
    MDG("Madagascar", "450", "MG", "MDG", "+261", "MGA", "AF"),
    MWI("Malawi", "454", "MW", "MWI", "+265", "MWK", "AF"),
    MYS("Malaysia", "458", "MY", "MYS", "+60", "MYR", "AS"),
    MDV("Maldives", "462", "MV", "MDV", "+960", "MVR", "AS"),
    MLI("Mali", "466", "ML", "MLI", "+223", "XOF", "AF"),
    MLT("Malta", "470", "MT", "MLT", "+356", "EUR", "EU"),
    MHL("Marshall Islands", "584", "MH", "MHL", "+692", "USD", "OC"),
    MTQ("Martinique", "474", "MQ", "MTQ", "+596", "EUR", "NA"),
    MRT("Mauritania", "478", "MR", "MRT", "+222", "MRO", "AF"),
    MUS("Mauritius", "480", "MU", "MUS", "+230", "MUR", "AF"),
    MYT("Mayotte", "175", "YT", "MYT", "+262", "EUR", "AF"),
    MEX("Mexico", "484", "MX", "MEX", "+52", "MXN", "NA"),
    FSM("Micronesia", "583", "FM", "FSM", "+691", "USD", "OC"),
    MDA("Moldova", "498", "MD", "MDA", "+373", "MDL", "EU"),
    MCO("Monaco", "492", "MC", "MCO", "+355", "EUR", "EU"),
    MNG("Mongolia", "496", "MN", "MNG", "+976", "MNT", "AS"),
    MNE("Montenegro", "499", "ME", "MNE", "+382", "EUR", "EU"),
    MSR("Montserrat", "500", "MS", "MSR", "+664", "XCD", "NA"),
    MAR("Morocco", "504", "MA", "MAR", "+212", "MAD", "AF"),
    MOZ("Mozambique", "508", "MZ", "MOZ", "+258", "MZN", "AF"),
    MMR("Myanmar", "104", "MM", "MMR", "+95", "MMK", "AS"),
    NAM("Namibia", "516", "NA", "NAM", "+264", "NAD", "AF"),
    NRU("Nauru", "520", "NR", "NRU", "+674", "AUD", "OC"),
    NPL("Nepal", "524", "NP", "NPL", "+977", "NPR", "AS"),
    NLD("Netherlands", "528", "NL", "NLD", "+31", "EUR", "EU"),
    NCL("New Caledonia", "540", "NC", "NCL", "+687", "XPF", "OC"),
    NZL("New Zealand", "554", "NZ", "NZL", "+64", "NZD", "OC"),
    NIC("Nicaragua", "558", "NI", "NIC", "+505", "NIO", "NA"),
    NER("Niger", "562", "NE", "NER", "+277", "XOF", "AF"),
    NGA("Nigeria", "566", "NG", "NGA", "+234", "NGN", "AF"),
    NIU("Niue", "570", "NU", "NIU", "+683", "NZD", "OC"),
    NFK("Norfolk Island", "574", "NF", "NFK", "+672", "AUD", "OC"),
    PRK("North Korea", "408", "KP", "PRK", "+850", "KPW", "AS"),
    NOR("Norway", "578", "NO", "NOR", "+47", "NOK", "EU"),
    OMN("Oman", "512", "OM", "OMN", "+968", "OMR", "AS"),
    PAK("Pakistan", "586", "PK", "PAK", "+92", "PKR", "AS"),
    PLW("Palau", "585", "PW", "PLW", "+680", "USD", "OC"),
    PSE("Palestinn Territories", "275", "PS", "PSE", "+970", "JOD", "AS"),
    PAN("Panama", "591", "PA", "PAN", "+507", "PAB", "NA"),
    PNG("Papua New Guinea", "598", "PG", "PNG", "+675", "PGK", "OC"),
    PRY("Paraguay", "600", "PY", "PRY", "+595", "PYG", "SA"),
    PER("Peru", "604", "PE", "PER", "+51", "PEN", "SA"),
    PHL("Philippines", "608", "PH", "PHL", "+63", "PHP", "AS"),
    PCN("Pitcairn", "612", "PN", "PCN", "+872", "NZD", "OC"),
    POL("Poland", "616", "PL", "POL", "+48", "PLN", "EU"),
    PRT("Portugal", "620", "PT", "PRT", "+351", "EUR", "EU"),
    PRI("Puerto Rico", "630", "PR", "PRI", "+787", "USD", "NA"),
    QAT("Qatar", "634", "QA", "QAT", "+974", "QAR", "AS"),
    REU("Réunion", "638", "RE", "REU", "+262", "EUR", "AF"),
    ROU("Romania", "642", "RO", "ROU", "+40", "RON", "EU"),
    RUS("Russia", "643", "RU", "RUS", "+7", "RUB", "EU"),
    RWA("Rwanda", "646", "RW", "RWA", "+250", "RWF", "AF"),
    KNA("St. Kitts and Nevis", "659", "KN", "KNA", "+869", "XCD", "NA"),
    LCA("St. Lucia", "662", "LC", "LCA", "+758", "XCD", "NA"),
    SPM("St. Pierre and Miquelon", "666", "PM", "SPM", "+508", "EUR", "NA"),
    VCT("St. Vincent and the Grenadines", "670", "VC", "VCT", "+784", "XCD", "NA"),
    WSM("Samoa", "882", "WS", "WSM", "+685", "WST", "OC"),
    SMR("San Marino", "674", "SM", "SMR", "+378", "EUR", "EU"),
    SAU("Saudi Arabia", "682", "SA", "SAU", "+966", "SAR", "AS"),
    SEN("Senegal", "686", "SN", "SEN", "+221", "XOF", "AF"),
    SRB("Serbia", "688", "RS", "SRB", "+381", "RSD", "EU"),
    SYC("Seychelles", "690", "SC", "SYC", "+248", "SCR", "AF"),
    SLE("Sierra Leone", "694", "SL", "SLE", "+232", "SLL", "AF"),
    SGP("Singapore", "702", "SG", "SGP", "+65", "SGD", "AS"),
    SVK("Slovakia", "703", "SK", "SVK", "+421", "SKK", "EU"),
    SVN("Slovenia", "705", "SI", "SVN", "+386", "EUR", "EU"),
    SLB("Solomon Islands", "090", "SB", "SLB", "+677", "SBD", "OC"),
    SOM("Somalia", "706", "SO", "SOM", "+252", "SOS", "AF"),
    ZAF("South Africa", "710", "ZA", "ZAF", "+27", "ZAR", "AF"),
    SSD("South Sudan", "728", "SS", "SSD", "+211", "SSP", ""),
    ESP("Spain", "724", "ES", "ESP", "+34", "EUR", "EU"),
    LKA("Sri Lanka", "144", "LK", "LKA", "+94", "LKR", "AS"),
    SDN("Sudan", "729", "SD", "SDN", "+249", "SDG", "AF"),
    SUR("Suriname", "740", "SR", "SUR", "+597", "SRD", "SA"),
    SJM("Svalbard and Jan Mayen", "744", "SJ", "SJM", "+47", "NOK", "EU"),
    SWZ("Swaziland", "748", "SZ", "SWZ", "+268", "CHF", "AF"),
    SWE("Sweden", "752", "SE", "SWE", "+46", "SEK", "EU"),
    CHE("Switzerland", "756", "CH", "CHE", "+41", "CHF", "EU"),
    SYR("Syria", "760", "SY", "SYR", "+963", "SYP", "AS"),
    TWN("Taiwan", "158", "TW", "TWN", "+886", "TWD", "AS"),
    TJK("Tajikistan", "762", "TJ", "TJK", "+992", "TJS", "AS"),
    TZA("Tanzania", "834", "TZ", "TZA", "+255", "TZS", "AF"),
    THA("Thailand", "764", "TH", "THA", "+66", "THB", "AS"),
    TLS("Timor-Leste", "626", "TL", "TLS", "+670", "IDR", "AS"),
    TGO("Togo", "768", "TG", "TGO", "+228", "XOF", "AF"),
    TKL("Tokelau", "772", "TK", "TKL", "+690", "NZD", "OC"),
    TON("Tonga", "776", "TO", "TON", "+676", "TOP", "OC"),
    TTO("Trinidad & Tobago", "780", "TT", "TTO", "+868", "TTD", "NA"),
    TUN("Tunisia", "788", "TN", "TUN", "+216", "TND", "AF"),
    TUR("Turkey", "792", "TR", "TUR", "+90", "TRY", "EU"),
    TKM("Turkmenistan", "795", "TM", "TKM", "+993", "TMM", "AS"),
    TCA("Turks & Caicos Islands", "796", "TC", "TCA", "+649", "USD", "NA"),
    TUV("Tuvalu", "798", "TV", "TUV", "+688", "TVD", "OC"),
    UGA("Uganda", "800", "UG", "UGA", "+256", "UGX", "AF"),
    UKR("Ukraine", "804", "UA", "UKR", "+380", "UAH", "EU"),
    ARE("United Arab Emirates", "784", "AE", "ARE", "+971", "AED", "AS"),
    GBR("United Kingdom", "826", "GB", "GBR", "+44", "GBP", "EU"),
    USA("United States", "840", "US", "USA", "+1", "USD", "NA"),
    UMI("U.S. Virgin Islands", "581", "UM", "UMI", "+1", "USD", "OC"),
    URY("Uruguay", "858", "UY", "URY", "+598", "UYU", "SA"),
    UZB("Uzbekistan", "860", "UZ", "UZB", "+998", "UZS", "AS"),
    VUT("Vanuatu", "548", "VU", "VUT", "+678", "VUV", "OC"),
    VEN("Venezuela", "862", "VE", "VEN", "+58", "VEF", "SA"),
    VNM("Vietnam", "704", "VN", "VNM", "+84", "VND", "AS"),
    YEM("Yemen", "887", "YE", "YEM", "+967", "YER", "AS"),
    ZMB("Zambia", "894", "ZM", "ZMB", "+260", "ZMW", "AF"),
    ZWE("Zimbabwe", "716", "ZW", "ZWE", "+263", "ZWD", "AF");

    private String name;
    private String numeric;
    private String alpha2;
    private String alpha3;
    private String calling;
    private String currency;
    private String continent;

    public static Country3 ofAlpha2(String alpha2) {
        return Arrays.stream(Country3.values())
                .filter(country3 -> country3.alpha2.equalsIgnoreCase(alpha2))
                .findAny()
                .orElse(null);
    }

    public static Country3 ofAlpha3(String alpha3) throws CashmallowException {
        return Arrays.stream(Country3.values())
                .filter(country3 -> country3.alpha3.equalsIgnoreCase(alpha3))
                .findAny()
                .orElseThrow(() -> new CashmallowException("PASSPORT COUNTRY CODE가 올바르지 않습니다 : " + NOT_FOUND_PASSPORT_COUNTRY_CODE));
    }

    public static Country3 ofCallingCode(String callingCode) {
        return Arrays.stream(Country3.values())
                .filter(country3 -> country3.calling.equalsIgnoreCase("+" + callingCode))
                .findAny()
                .orElse(null);
    }

}
