package com.cashmallow.api.domain.model.country.enums;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Getter;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * 회원가입시 사용할 iso3166 값등 국가 정보
 * 순서대로 노출됨.
 */

@JsonFormat(shape = JsonFormat.Shape.OBJECT)
@AllArgsConstructor
@Getter
public enum CountryInfo implements Serializable {
    KR("South Korea", "410", "KR", "KOR", "+82", "KRW", "AS"),
    HK("Hong Kong", "344", "HK", "HKG", "+852", "HKD", "AS"),

    AF("Afghanistan", "004", "AF", "AFG", "+93", "AFN", "AS"),
    AL("Albania", "008", "AL", "ALB", "+355", "ALL", "EU"),
    DZ("Algeria", "012", "DZ", "DZA", "+213", "DZD", "AF"),
    AS("American Samoa", "016", "AS", "ASM", "+684", "USD", "OC"),
    AD("Andorra", "020", "AD", "AND", "+376", "EUR", "EU"),
    AO("Angola", "024", "AO", "AGO", "+244", "AOA", "AF"),
    AI("Anguilla", "660", "AI", "AIA", "+264", "XCD", "NA"),
    AQ("Antarctica", "010", "AQ", "ATA", "+672", "AUD", "AN"),
    AG("Antigua & Barbuda", "028", "AG", "ATG", "+268", "XCD", "NA"),
    AR("Argentina", "032", "AR", "ARG", "+54", "ARS", "SA"),
    AM("Armenia", "051", "AM", "ARM", "+374", "AMD", "AS"),
    AW("Aruba", "533", "AW", "ABW", "+297", "AWG", "NA"),
    AU("Australia", "036", "AU", "AUS", "+61", "AUD", "OC"),
    AT("Austria", "040", "AT", "AUT", "+43", "EUR", "EU"),
    AZ("Azerbaijan", "031", "AZ", "AZE", "+994", "AZN", "AS"),
    BS("Bahamas", "044", "BS", "BHS", "+242", "BSD", "NA"),
    BH("Bahrain", "048", "BH", "BHR", "+973", "BHD", "AS"),
    BD("Bangladesh", "050", "BD", "BGD", "+880", "BDT", "AS"),
    BB("Barbados", "052", "BB", "BRB", "+246", "BBD", "NA"),
    BY("Belarus", "112", "BY", "BLR", "+375", "BYR", "EU"),
    BE("Belgium", "056", "BE", "BEL", "+32", "EUR", "EU"),
    BZ("Belize", "084", "BZ", "BLZ", "+501", "BZD", "NA"),
    BJ("Benin", "204", "BJ", "BEN", "+229", "XOF", "AF"),
    BM("Bermuda", "060", "BM", "BMU", "+441", "BMD", "NA"),
    BT("Bhutan", "064", "BT", "BTN", "+975", "BTN", "AS"),
    BO("Bolivia", "068", "BO", "BOL", "+591", "BOB", "SA"),
    BA("Bosnia & Herzegovina", "070", "BA", "BIH", "+387", "BAM", "EU"),
    BW("Botswana", "072", "BW", "BWA", "+267", "BWP", "AF"),
    BR("Brazil", "076", "BR", "BRA", "+55", "BRL", "SA"),
    VG("British Virgin Islands", "092", "VG", "VGB", "+1", "USD", "NA"),
    BN("Brunei", "096", "BN", "BRN", "+673", "BND", "AS"),
    BG("Bulgaria", "100", "BG", "BGR", "+359", "EUR", "EU"),
    BF("Burkina Faso", "854", "BF", "BFA", "+226", "XOF", "AF"),
    BI("Burundi", "108", "BI", "BDI", "+257", "BIF", "AF"),
    KH("Cambodia", "116", "KH", "KHM", "+855", "KHR", "AS"),
    CM("Cameroon", "120", "CM", "CMR", "+237", "XAF", "AF"),
    CA("Canada", "124", "CA", "CAN", "+1", "CAD", "NA"),
    CV("Cabo Verde", "132", "CV", "CPV", "+238", "CVE", "AF"),
    KY("Cayman Islands", "136", "KY", "CYM", "+345", "KYD", "NA"),
    CF("Central African Republic", "140", "CF", "CAF", "+236", "XAF", "AF"),
    TD("Chad", "148", "TD", "TCD", "+235", "XAF", "AF"),
    CL("Chile", "152", "CL", "CHL", "+56", "CLP", "SA"),
    CN("China", "156", "CN", "CHN", "+86", "CNY", "AS"),
    CO("Colombia", "170", "CO", "COL", "+57", "COP", "SA"),
    KM("Comoros", "174", "KM", "COM", "+269", "KMF", "AF"),
    CG("Congo - Brazzaville", "178", "CG", "COG", "+242", "XAF", "AF"),
    CD("Congo - Kinshasa", "180", "CD", "COD", "+243", "CDF", "AF"),
    CK("Cook Islands", "184", "CK", "COK", "+682", "NZD", "OC"),
    CR("Costa Rica", "188", "CR", "CRI", "+506", "CRC", "NA"),
    CI("Côte d'Ivoire", "384", "CI", "CIV", "+225", "XOF", "AF"),
    HR("Croatia", "191", "HR", "HRV", "+385", "HRK", "EU"),
    CU("Cuba", "192", "CU", "CUB", "+53", "CUP", "NA"),
    CW("Curaçao", "531", "CW", "CUW", "+599", "ANG", ""),
    CY("Cyprus", "196", "CY", "CYP", "+357", "EUR", "AS"),
    CZ("Czech Republic", "203", "CZ", "CZE", "+420", "CZK", "EU"),
    DK("Denmark", "208", "DK", "DNK", "+45", "EUR", "EU"),
    DJ("Djibouti", "262", "DJ", "DJI", "+253", "DJF", "AF"),
    DM("Dominica", "212", "DM", "DMA", "+767", "XCD", "NA"),
    DO("Dominican Republic", "214", "DO", "DOM", "+809", "DOP", "NA"),
    EC("Ecuador", "218", "EC", "ECU", "+593", "USD", "SA"),
    EG("Egypt", "818", "EG", "EGY", "+20", "EGP", "AF"),
    SV("El Salvador", "222", "SV", "SLV", "+503", "SVC", "NA"),
    GQ("Equatorial Guinea", "226", "GQ", "GNQ", "+240", "XAF", "AF"),
    ER("Eritrea", "232", "ER", "ERI", "+291", "ETB", "AF"),
    EE("Estonia", "233", "EE", "EST", "+372", "EUR", "EU"),
    ET("Ethiopia", "231", "ET", "ETH", "+251", "ETB", "AF"),
    FK("Falkland Islands", "238", "FK", "FLK", "+500", "FKP", "SA"),
    FO("Faroe Islands", "234", "FO", "FRO", "+298", "DKK", "EU"),
    FJ("Fiji", "242", "FJ", "FJI", "+679", "FJD", "OC"),
    FI("Finland", "246", "FI", "FIN", "+358", "EUR", "EU"),
    FR("France", "250", "FR", "FRA", "+33", "EUR", "EU"),
    GF("French Guiana", "254", "GF", "GUF", "+594", "EUR", "SA"),
    PF("French Polynesia", "258", "PF", "PYF", "+689", "XPF", "OC"),
    GA("Gabon", "266", "GA", "GAB", "+241", "XAF", "AF"),
    GM("Gambia", "270", "GM", "GMB", "+220", "GMD", "AF"),
    GE("Georgia", "268", "GE", "GEO", "+995", "GEL", "AS"),
    DE("Germany", "276", "DE", "DEU", "+49", "EUR", "EU"),
    GH("Ghana", "288", "GH", "GHA", "+233", "GHS", "AF"),
    GI("Gibraltar", "292", "GI", "GIB", "+350", "GIP", "EU"),
    GR("Greece", "300", "GR", "GRC", "+30", "EUR", "EU"),
    GL("Greenland", "304", "GL", "GRL", "+299", "DKK", "NA"),
    GD("Grenada", "308", "GD", "GRD", "+473", "XCD", "NA"),
    GP("Guadeloupe", "312", "GP", "GLP", "+590", "EUR", "NA"),
    GU("Guam", "316", "GU", "GUM", "+671", "USD", "OC"),
    GT("Guatemala", "320", "GT", "GTM", "+502", "GTQ", "NA"),
    GG("Guernsey", "831", "GG", "GGY", "+1481", "GGP", "EU"),
    GN("Guinea", "324", "GN", "GIN", "+225", "GNF", "AF"),
    GW("Guinea-Bissau", "624", "GW", "GNB", "+245", "XOF", "AF"),
    GY("Guyana", "328", "GY", "GUY", "+592", "GYD", "SA"),
    HT("Haiti", "332", "HT", "HTI", "+509", "HTG", "NA"),
    HN("Honduras", "340", "HN", "HND", "+504", "HNL", "NA"),
    HU("Hungary", "348", "HU", "HUN", "+36", "HUF", "EU"),
    IS("Iceland", "352", "IS", "ISL", "+354", "ISK", "EU"),
    IN("India", "356", "IN", "IND", "+91", "INR", "AS"),
    ID("Indonesia", "360", "ID", "IDN", "+62", "IDR", "AS"),
    IR("Iran", "364", "IR", "IRN", "+98", "IRR", "AS"),
    IQ("Iraq", "368", "IQ", "IRQ", "+964", "IQD", "AS"),
    IE("Ireland", "372", "IE", "IRL", "+353", "EUR", "EU"),
    IL("Israel", "376", "IL", "ISR", "+972", "ILS", "AS"),
    IT("Italy", "380", "IT", "ITA", "+39", "EUR", "EU"),
    JM("Jamaica", "388", "JM", "JAM", "+876", "JMD", "NA"),
    JP("Japan", "392", "JP", "JPN", "+81", "JPY", "AS"),
    JO("Jordan", "400", "JO", "JOR", "+962", "JOD", "AS"),
    KZ("Kazakhstan", "398", "KZ", "KAZ", "+7", "KZT", "AS"),
    KE("Kenya", "404", "KE", "KEN", "+254", "KES", "AF"),
    KI("Kiribati", "296", "KI", "KIR", "+686", "AUD", "OC"),
    KW("Kuwait", "414", "KW", "KWT", "+965", "KWD", "AS"),
    KG("Kyrgyzstan", "417", "KG", "KGZ", "+996", "KGS", "AS"),
    LA("Laos", "418", "LA", "LAO", "+856", "LAK", "AS"),
    LV("Latvia", "428", "LV", "LVA", "+371", "EUR", "EU"),
    LB("Lebanon", "422", "LB", "LBN", "+961", "LBP", "AS"),
    LS("Lesotho", "426", "LS", "LSO", "+266", "LSL", "AF"),
    LR("Liberia", "430", "LR", "LBR", "+231", "LRD", "AF"),
    LY("Libya", "434", "LY", "LBY", "+218", "LYD", "AF"),
    LI("Liechtenstein", "438", "LI", "LIE", "+423", "CHF", "EU"),
    LT("Lithuania", "440", "LT", "LTU", "+370", "EUR", "EU"),
    LU("Luxembourg", "442", "LU", "LUX", "+352", "EUR", "EU"),
    MO("Macao", "446", "MO", "MAC", "+853", "MOP", "AS"),
    MK("Macedonia", "807", "MK", "MKD", "+389", "MKD", "EU"),
    MG("Madagascar", "450", "MG", "MDG", "+261", "MGA", "AF"),
    MW("Malawi", "454", "MW", "MWI", "+265", "MWK", "AF"),
    MY("Malaysia", "458", "MY", "MYS", "+60", "MYR", "AS"),
    MV("Maldives", "462", "MV", "MDV", "+960", "MVR", "AS"),
    ML("Mali", "466", "ML", "MLI", "+223", "XOF", "AF"),
    MT("Malta", "470", "MT", "MLT", "+356", "EUR", "EU"),
    MH("Marshall Islands", "584", "MH", "MHL", "+692", "USD", "OC"),
    MQ("Martinique", "474", "MQ", "MTQ", "+596", "EUR", "NA"),
    MR("Mauritania", "478", "MR", "MRT", "+222", "MRO", "AF"),
    MU("Mauritius", "480", "MU", "MUS", "+230", "MUR", "AF"),
    YT("Mayotte", "175", "YT", "MYT", "+262", "EUR", "AF"),
    MX("Mexico", "484", "MX", "MEX", "+52", "MXN", "NA"),
    FM("Micronesia", "583", "FM", "FSM", "+691", "USD", "OC"),
    MD("Moldova", "498", "MD", "MDA", "+373", "MDL", "EU"),
    MC("Monaco", "492", "MC", "MCO", "+355", "EUR", "EU"),
    MN("Mongolia", "496", "MN", "MNG", "+976", "MNT", "AS"),
    ME("Montenegro", "499", "ME", "MNE", "+382", "EUR", "EU"),
    MS("Montserrat", "500", "MS", "MSR", "+664", "XCD", "NA"),
    MA("Morocco", "504", "MA", "MAR", "+212", "MAD", "AF"),
    MZ("Mozambique", "508", "MZ", "MOZ", "+258", "MZN", "AF"),
    MM("Myanmar", "104", "MM", "MMR", "+95", "MMK", "AS"),
    NA("Namibia", "516", "NA", "NAM", "+264", "NAD", "AF"),
    NR("Nauru", "520", "NR", "NRU", "+674", "AUD", "OC"),
    NP("Nepal", "524", "NP", "NPL", "+977", "NPR", "AS"),
    NL("Netherlands", "528", "NL", "NLD", "+31", "EUR", "EU"),
    NC("New Caledonia", "540", "NC", "NCL", "+687", "XPF", "OC"),
    NZ("New Zealand", "554", "NZ", "NZL", "+64", "NZD", "OC"),
    NI("Nicaragua", "558", "NI", "NIC", "+505", "NIO", "NA"),
    NE("Niger", "562", "NE", "NER", "+277", "XOF", "AF"),
    NG("Nigeria", "566", "NG", "NGA", "+234", "NGN", "AF"),
    NU("Niue", "570", "NU", "NIU", "+683", "NZD", "OC"),
    NF("Norfolk Island", "574", "NF", "NFK", "+672", "AUD", "OC"),
    // KP("North Korea", "408", "KP", "PRK", "+850", "KPW", "AS"),
    NO("Norway", "578", "NO", "NOR", "+47", "NOK", "EU"),
    OM("Oman", "512", "OM", "OMN", "+968", "OMR", "AS"),
    PK("Pakistan", "586", "PK", "PAK", "+92", "PKR", "AS"),
    PW("Palau", "585", "PW", "PLW", "+680", "USD", "OC"),
    PS("Palestinn Territories", "275", "PS", "PSE", "+970", "JOD", "AS"),
    PA("Panama", "591", "PA", "PAN", "+507", "PAB", "NA"),
    PG("Papua New Guinea", "598", "PG", "PNG", "+675", "PGK", "OC"),
    PY("Paraguay", "600", "PY", "PRY", "+595", "PYG", "SA"),
    PE("Peru", "604", "PE", "PER", "+51", "PEN", "SA"),
    PH("Philippines", "608", "PH", "PHL", "+63", "PHP", "AS"),
    PN("Pitcairn", "612", "PN", "PCN", "+872", "NZD", "OC"),
    PL("Poland", "616", "PL", "POL", "+48", "EUR", "EU"),
    PT("Portugal", "620", "PT", "PRT", "+351", "EUR", "EU"),
    PR("Puerto Rico", "630", "PR", "PRI", "+787", "USD", "NA"),
    QA("Qatar", "634", "QA", "QAT", "+974", "QAR", "AS"),
    RE("Réunion", "638", "RE", "REU", "+262", "EUR", "AF"),
    RO("Romania", "642", "RO", "ROU", "+40", "RON", "EU"),
    RU("Russia", "643", "RU", "RUS", "+7", "RUB", "EU"),
    RW("Rwanda", "646", "RW", "RWA", "+250", "RWF", "AF"),
    KN("St. Kitts and Nevis", "659", "KN", "KNA", "+869", "XCD", "NA"),
    LC("St. Lucia", "662", "LC", "LCA", "+758", "XCD", "NA"),
    PM("St. Pierre and Miquelon", "666", "PM", "SPM", "+508", "EUR", "NA"),
    VC("St. Vincent and the Grenadines", "670", "VC", "VCT", "+784", "XCD", "NA"),
    WS("Samoa", "882", "WS", "WSM", "+685", "WST", "OC"),
    SM("San Marino", "674", "SM", "SMR", "+378", "EUR", "EU"),
    SA("Saudi Arabia", "682", "SA", "SAU", "+966", "SAR", "AS"),
    SN("Senegal", "686", "SN", "SEN", "+221", "XOF", "AF"),
    RS("Serbia", "688", "RS", "SRB", "+381", "RSD", "EU"),
    SC("Seychelles", "690", "SC", "SYC", "+248", "SCR", "AF"),
    SL("Sierra Leone", "694", "SL", "SLE", "+232", "SLL", "AF"),
    SG("Singapore", "702", "SG", "SGP", "+65", "SGD", "AS"),
    SK("Slovakia", "703", "SK", "SVK", "+421", "SKK", "EU"),
    SI("Slovenia", "705", "SI", "SVN", "+386", "EUR", "EU"),
    SB("Solomon Islands", "090", "SB", "SLB", "+677", "SBD", "OC"),
    SO("Somalia", "706", "SO", "SOM", "+252", "SOS", "AF"),
    ZA("South Africa", "710", "ZA", "ZAF", "+27", "ZAR", "AF"),
    SS("South Sudan", "728", "SS", "SSD", "+211", "SSP", ""),
    ES("Spain", "724", "ES", "ESP", "+34", "EUR", "EU"),
    LK("Sri Lanka", "144", "LK", "LKA", "+94", "LKR", "AS"),
    SD("Sudan", "729", "SD", "SDN", "+249", "SDG", "AF"),
    SR("Suriname", "740", "SR", "SUR", "+597", "SRD", "SA"),
    SJ("Svalbard and Jan Mayen", "744", "SJ", "SJM", "+47", "NOK", "EU"),
    SZ("Swaziland", "748", "SZ", "SWZ", "+268", "CHF", "AF"),
    SE("Sweden", "752", "SE", "SWE", "+46", "EUR", "EU"),
    CH("Switzerland", "756", "CH", "CHE", "+41", "CHF", "EU"),
    SY("Syria", "760", "SY", "SYR", "+963", "SYP", "AS"),
    TW("Taiwan", "158", "TW", "TWN", "+886", "TWD", "AS"),
    TJ("Tajikistan", "762", "TJ", "TJK", "+992", "TJS", "AS"),
    TZ("Tanzania", "834", "TZ", "TZA", "+255", "TZS", "AF"),
    TH("Thailand", "764", "TH", "THA", "+66", "THB", "AS"),
    TL("Timor-Leste", "626", "TL", "TLS", "+670", "IDR", "AS"),
    TG("Togo", "768", "TG", "TGO", "+228", "XOF", "AF"),
    TK("Tokelau", "772", "TK", "TKL", "+690", "NZD", "OC"),
    TO("Tonga", "776", "TO", "TON", "+676", "TOP", "OC"),
    TT("Trinidad & Tobago", "780", "TT", "TTO", "+868", "TTD", "NA"),
    TN("Tunisia", "788", "TN", "TUN", "+216", "TND", "AF"),
    TR("Turkey", "792", "TR", "TUR", "+90", "TRY", "EU"),
    TM("Turkmenistan", "795", "TM", "TKM", "+993", "TMM", "AS"),
    TC("Turks & Caicos Islands", "796", "TC", "TCA", "+649", "USD", "NA"),
    TV("Tuvalu", "798", "TV", "TUV", "+688", "TVD", "OC"),
    UG("Uganda", "800", "UG", "UGA", "+256", "UGX", "AF"),
    UA("Ukraine", "804", "UA", "UKR", "+380", "UAH", "EU"),
    AE("United Arab Emirates", "784", "AE", "ARE", "+971", "AED", "AS"),
    GB("United Kingdom", "826", "GB", "GBR", "+44", "GBP", "EU"),
    US("United States", "840", "US", "USA", "+1", "USD", "NA"),
    UM("U.S. Virgin Islands", "581", "UM", "UMI", "+1", "USD", "OC"),
    UY("Uruguay", "858", "UY", "URY", "+598", "UYU", "SA"),
    UZ("Uzbekistan", "860", "UZ", "UZB", "+998", "UZS", "AS"),
    VU("Vanuatu", "548", "VU", "VUT", "+678", "VUV", "OC"),
    VE("Venezuela", "862", "VE", "VEN", "+58", "VEF", "SA"),
    VN("Vietnam", "704", "VN", "VNM", "+84", "VND", "AS"),
    YE("Yemen", "887", "YE", "YEM", "+967", "YER", "AS"),
    ZM("Zambia", "894", "ZM", "ZMB", "+260", "ZMW", "AF"),
    ZW("Zimbabwe", "716", "ZW", "ZWE", "+263", "ZWD", "AF");

    private String name;
    private String numeric;
    private String alpha2;
    private String alpha3;
    private String calling;
    private String currency;
    private String continent;

    public static final Map<String, String> callingPrefix = Arrays.stream(CountryInfo.values()).collect(Collectors.toUnmodifiableMap(CountryInfo::getAlpha3, CountryInfo::getCalling));
}
